### ISSUE TITLE
An error when working on reference router 1g cml

### ISSUE THREAD

**Issue by Shandongwzl** [NetFPGA/netfpga#18]
I am working on NetFPGA 1G CML.
My system is Centos 7. My ISE is 14.6 and Vivado is 15.2.
I have already succeeded in generating the bitfile of the project reference_nic_1g_cml.
Yet I got an error when try to generate the bitfile of reference_router_1g_cml at step 4.
I do follow the instructions of the readme:
[https://github.com/NetFPGA/NetFPGA-1G-CML-live/tree/master/projects/reference_router_nf1_cml](url)
The error message is as follows:

[error.log](https://github.com/NetFPGA/netfpga/files/4650681/error.log)

Could you please tell me where the problem lies?
Thank you very much.

**Comment by salvatorg** [comment]
Duplicate post.
[Issue #16](https://github.com/NetFPGA/NetFPGA-1G-CML-live/issues/16#issuecomment-631467199)
