### ISSUE TITLE
packet_generator problem

### ISSUE THREAD

**Issue by afuyuan** [NetFPGA/netfpga#2]
i have download this packet_generator_1.1.1 on windows and unzip it get folder of netfpga,it including two folders (bidfiles,projects)and one LICENSE.,Then i update the ISE to 10.1SP3,
i copied packet_generator_1.1.1 from netfpga/projects to ~/netfpga/projects,and modify project.xml
replace core/io_queues/ethernet_mac
with
replace core/io_queues/ethernet_queue
contrib/ucsd/gig_eth_mac
when i go to ~/netfpga/projects/packet_generator/synth and type make
i get a error that i can not solve it！！！
can you help to solve it
thank you!!!!!!

Analysis of file <"nf2_top.prj"> succeeded.

================================================== =======================
- Design Hierarchy Analysis *
  ================================================== =======================
  ERROR:HDLCompilers:87 - "../src/nf2_mac_grp.v" line 114 Could not find module/primitive 'tri_mode_eth_mac'
  -->

Total memory usage is 126992 kilobytes

Number of errors : 1 ( 0 filtered)
Number of warnings : 0 ( 0 filtered)
Number of infos : 0 ( 0 filtered)

Synthesis failed - see nf2_top.srp for details.
make: **\* [nf2_top.ngc] 错误 1

**Comment by afuyuan** [comment]
i do this want run the packet_generator.
i get version against to CPCI,if i use nf_down to download the packet_generator.bit which unzip from netfpga_packet_generator_1_1_1.tar.gz.
please,help

**Comment by manihatn** [comment]
The error you mentioned "Could not find module/primitive 'tri_mode_eth_mac' -->", relates to either you don't have the the license for the ipcore "tri_mode_eth_mac" or the file can be missing. Can you please check this.  

Also please have a look at the OS requirements for the NetFPGA 1G systems, NetFPGA 1G runs on Fedora 14. You can find details below.

https://github.com/NetFPGA/netfpga/wiki/InstallSoftware#wiki-Installing_an_Operating_System_on_the_Host_PC

HTH,
Neels

**Comment by afuyuan** [comment]
thank you!!!
i replay a IPcore from xilinx.com and sloved it
!!!
