### ISSUE TITLE
Links for schematics files in wiki do not work

### ISSUE THREAD

**Issue by jaspersalathe** [NetFPGA/netfpga#3]
The links for the schematics files in the wiki ( https://github.com/NetFPGA/netfpga/wiki/Guide#schematic-and-board-layout ) do not work.
Is there somehow a possibility to make those available?

**Comment by Caustic** [comment]
I fixed it.  The netfpga team changed the wiki to a subdomain before moving to github.  i.e. wiki.netfpga.org/resource

If you notice any more broken links, try that out and update the wiki if it works!  :-)

Cheers!

**Comment by manihatn** [comment]
Thanks caustic, I appreciate it..

**Comment by jaspersalathe** [comment]
thanks a lot for your fast reply =)

**Comment by Be4stElectrjc** [comment]
Hi, did the domain change again?

Thanks, all the best
